### ISSUE TITLE
No idea what to do with requirements. Please provide how to?

### ISSUE THREAD

**Issue by penguinroad** [khairul169/gdsqlite-native#1]
Hi. I'm interested in using sqlite with godot. I see you've done gdnative for sqlite which is awesome. 

You stated clearly in your readme that your lib require godot_headers and cpp_bindings so I clone the git. But I have no idea what to do with them. And their readme is not very helpful. One is confusing and one basically contains nothing

So can you be so kind to provide a how to setup and compile godot so I can give a try your lib?

I'm on Ubuntu 16.04 btw. And I already can compile godot source code

Thanks in advance

**Comment by khairul169** [comment]
Godot headers & cpp bindings are needed to compile this lib from source.. Just clone both of the repository, and compile only the cpp bindings.. There are no documentation on how to compile cpp bindings, but you can install composer to generate bindings and playing with the SConstruct file 😅 you can also download the compiled cpp bindings from https://github.com/GodotNativeTools/cpp_bindings/releases/download/starter_kit/godot_cpp_starter_kit.zip :3

**Comment by khairul169** [comment]
About the engine, just compile it normally without modifying anything 😃  there is a sample project, you can open the project with master branch of godot

**Comment by penguinroad** [comment]
Thanks. I downloaded the starter kit, and copy libgodot_cpp_core.so and libgodot_cpp_bindings.so to where libsqlite.so is in your sample and it works.
