### ISSUE TITLE
Is not compatible with godot 3.0.4?

### ISSUE THREAD

**Issue by Saikol** [khairul169/gdsqlite-native#12]
Version:Godot 3.0.4
So:Elementary Os

I can not make the examples work in the version of godot 3.0.4 or is it only compatible with version3.0?

**Comment by Suvica** [comment]
Did you download the release? https://github.com/khairul169/gdsqlite-native/releases

I accidently got the master, and that won't work.

**Comment by Saikol** [comment]
Use the "Godot SQLite 1.2" version but I can not make it work or the demos work for me, so I asked if they only work for version 3.0 and not for 3.0.4

**Comment by squished-01** [comment]
It works with 3.0.5.

**Comment by PrinceMerluza** [comment]
Can't make the sample projects work. Also should we be using the singleton or direct reference?

![image](https://user-images.githubusercontent.com/22146579/45289603-2e968f00-b520-11e8-8b7f-65befd5fe745.png)

**Comment by khairul169** [comment]
@PrinceMerluza What godot version did you use?

**Comment by khairul169** [comment]
Master branch now support godot 3.1, and latest release support 3.0. I think this issue can be closed now.
