### ISSUE TITLE
error: 'class SQLite' has no member named 'owner'

### ISSUE THREAD

**Issue by MJ-meo-dmt** [khairul169/gdsqlite-native#2]
Hi Building on Linux Failed...

I had to adjust the SConstruct file in order to actually find all the things it needed. Still though it complained about some stuff.

Here is my current Sconstruct file:
`
#!python
import os

cpp_bindings = "./cpp_bindings"
godot_headers = "./godot_headers"
cpp_bindings_include = "./cpp_bindings/include"

env = Environment()

if ARGUMENTS.get("use_llvm", "no") == "yes":
    env["CXX"] = "clang++"

platform = ARGUMENTS.get("p", "linux")
bits = ARGUMENTS.get("bits", "64")

env.Append(CPPPATH=[godot_headers, cpp_bindings, cpp_bindings + '/include/core', cpp_bindings_include, 'src'])
env.Append(LIBS=['libgodot_cpp_core', 'libgodot_cpp_bindings'])
env.Append(LIBPATH=[cpp_bindings, "lib"])

env.Append(CCFLAGS = ['-g','-O3'])
env.Append(CXXFLAGS = ['-std=c++14', '-Wwrite-strings'])

if platform == "linux":
    env.Append(LINKFLAGS = ['-Wl,-R,\'$$ORIGIN\''])

if platform == "windows":
    env.Append(LIBS=['godot.windows.opt.tools.' + bits])

def add_source(sources, name):
    sources.append("src/" + name)

def add_sources(sources, dir, extension):
    for f in os.listdir("src/" + dir):
        if f.endswith("." + extension):
            sources.append("src/" + dir + "/" + f)

sources = []

add_source(sources, "init.cpp")
add_source(sources, "sqlite.cpp")

add_sources(sources, "sqlite", "c")

library = env.SharedLibrary(target=('lib/sqlite'), source=sources)
Default(library)
`

# And here is the resulting error:

`
/Development/GitHub/GDSqlite $ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/init.os -c -std=c++14 -Wwrite-strings -g -O3 -fPIC -Igodot_headers -Icpp_bindings -Icpp_bindings/include/core -Icpp_bindings/include -Isrc src/init.cpp
In file included from src/init.cpp:2:0:
src/sqlite.h:11:31: error: macro "GODOT_CLASS" passed 2 arguments, but takes just 1
  GODOT_CLASS(SQLite, Reference)
                               ^
src/sqlite.h:11:2: error: 'GODOT_CLASS' does not name a type
  GODOT_CLASS(SQLite, Reference)
  ^
In file included from src/init.h:4:0,
                 from src/init.cpp:1:
cpp_bindings/include/core/Godot.hpp: In instantiation of 'void godot::register_class() [with T = SQLite]':
src/init.cpp:5:28:   required from here
cpp_bindings/include/core/Godot.hpp:129:49: error: '___get_type_name' is not a member of 'SQLite'
  godot_script_register_class(T::___get_type_name(), T::___get_base_type_name(), create, destroy);
                                                 ^
cpp_bindings/include/core/Godot.hpp:129:77: error: '___get_base_type_name' is not a member of 'SQLite'
  godot_script_register_class(T::___get_type_name(), T::___get_base_type_name(), create, destroy);
                                                                             ^
In file included from src/init.cpp:2:0:
src/sqlite.h:23:14: error: 'static void SQLite::_register_methods()' is private
  static void _register_methods();
              ^
In file included from src/init.h:4:0,
                 from src/init.cpp:1:
cpp_bindings/include/core/Godot.hpp:130:22: error: within this context
  T::_register_methods();
                      ^
cpp_bindings/include/core/Godot.hpp: In instantiation of 'void* godot::_godot_class_instance_func(godot_object*, void*) [with T = SQLite; godot_object = void]':
cpp_bindings/include/core/Godot.hpp:123:21:   required from 'void godot::register_class() [with T = SQLite]'
src/init.cpp:5:28:   required from here
cpp_bindings/include/core/Godot.hpp:105:21: error: 'class SQLite' has no member named 'owner'
  *(godot_object **) &d->owner = p;
                     ^
scons: *** [src/init.os] Error 1
scons: building terminated because of errors.
`

**Comment by khairul169** [comment]
It seems that the problem are caused by godot cpp bindings itself..
Current module does not use cpp bindings again, so it is easy to compile for now.. you can try to compile it yourself or download latest release to use with your project 👍
