### ISSUE TITLE
Support for prepared statements

### ISSUE THREAD

**Issue by Antokolos** [khairul169/gdsqlite-native#28]
As I've understood, there is no support for prepared statements right now, therefore I'm forced to write the statements with parameters in the following way:
`db.query("UPDATE players SET player_name = '%s' WHERE steam_id = %d" % [player_name, steam_ID])`
which is obviously very dangerous because of potential [SQL injections](https://en.wikipedia.org/wiki/SQL_injection)
It would be very very nice, if support for [prepared statements](https://en.wikipedia.org/wiki/Prepared_statement) would be added.
Maybe, for example, these functions:
https://www.sqlite.org/c3ref/bind_blob.html

**Comment by Antokolos** [comment]
P.S.: and it would be super great, if we can do it in one line! :)
For example query above:
`db.query("UPDATE players SET player_name = '%s' WHERE steam_id = %d" % [player_name, steam_ID])`
should be changed to something like:
`db.query("UPDATE players SET player_name = ? WHERE steam_id = ?", player_name, steam_ID)`
and the library processes variables under the hood, determines the type of the variable and calls the corresponding sqlite3_bind_* function, if this is, of course, possible :)

**Comment by TGRCdev** [comment]
I put a bit of work into this. Right now, [I have it working](https://github.com/TGRCdev/gdsqlite-native/commit/db4bb430f2e7bbb9942ebaf6e99b314f694f2062) using an `Array` to pass arguments.

Unfortunately, now `query()` REQUIRES an `Array` for the second argument, even if it's empty. GDNative does not support variadic arguments, so I'm trying to see if I can make the default argument an empty Array.

Worst case scenario, I can make a new function called `query_with_args()`, and leave `query()` alone.

Thoughts?

**Comment by Antokolos** [comment]
Wow, great to hear that you already implemented it! Hope it gets merged into master soon!
As for the function names, in my opinion `query_with_args()` is acceptable, but let's see, what @khairul169 thinks about it.

**Comment by khairul169** [comment]
That was great, Thanks! :)
