### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by GrandFunkR** [khairul169/gdsqlite-native#3]
have a compile error also there are not releases at https://github.com/khairul169/gdsqlite-native/releases:

$ ./build.sh 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/init.os -c -std=c++14 -Wwrite-strings -g -O3 -fPIC -I/home/dario/tmp/native/godot_headers -I/home/dario/tmp/native/godot_cpp_bindings/include -I/home/dario/tmp/native/godot_cpp_bindings/include/godot_cpp -Isrc src/init.cpp
In file included from src/init.h:4:0,
                 from src/init.cpp:1:
/home/dario/tmp/native/godot_cpp_bindings/include/Godot.hpp:15:10: fatal error: Object.hpp: No such file or directory
 #include <Object.hpp>
          ^~~~~~~~~~~~
compilation terminated.
scons: *** [src/init.os] Error 1
scons: building terminated because of errors.
[dario@myhostname gdsqlite-native]$ cd ..
[dario@myhostname native]$ find . -name Object.hpp

**Comment by quendera** [comment]
This compile error persists...

**Comment by khairul169** [comment]
Fixed by commit d3854420cd1188b56401de01ed3ff2dc778499ce.. Closed then 💃
