### ISSUE TITLE
Support for Godot 3.1.1

### ISSUE THREAD

**Issue by squished-01** [khairul169/gdsqlite-native#30]
My editor crashes with no error messages (even in debug mode) about a minute after opening my project, and I strongly suspect it is the sqlite dll.  

Any chance of getting an official release that supports 3.1.1 ?

**Comment by TGRCdev** [comment]
I have compiled a [beta build](https://github.com/TGRCdev/gdsqlite-native/releases/tag/1.4-beta) for Windows, Linux and OSX on Godot 3.1. Let me know if these don't work for you.

**Comment by MarkuBu** [comment]
I tried this build on Ubuntu 18.04 64 Bit. Seems to work so far. 

But you should add a documentation how to build the lib from source. Currently I don't know how to do that

**Comment by TGRCdev** [comment]
I added an extra section to the README and opened a pull request. You can read the build guide [here](https://github.com/TGRCdev/gdsqlite-native/blob/build-instructions/README.md#compiling-from-source).
