### ISSUE TITLE
There are no releases

### ISSUE THREAD

**Issue by MarianoGnu** [khairul169/gdsqlite-native#4]
even thought readme says to download release and uncompress con the project directoy there are no files to download, it would be great to have a ready to use beta at least.

**Comment by MarianoGnu** [comment]
now i see that last commit is 7 months ago, since gdnative was refactored there's no way i can build this :/

**Comment by khairul169** [comment]
I've rebuild this module to work with the latest version of godot.. you can check out release page to download this library 💃

**Comment by khairul169** [comment]
Closed.
