### ISSUE TITLE
Support for blobs

### ISSUE THREAD

**Issue by toboRlivE** [khairul169/gdsqlite-native#41]
First, I'd like to say a big thank you for this tool! I was trying to implement this myself when I found a link here.

I'm trying to serialize binary data into and out of an sqlite db. My end-goal is to store and retrieve image data as well as feeding a binary node dump into a table. I was thinking of using  flatbuffers to feed in and out nodes. Then have those saved to blobs with extra columns for query information to narrow in on, but I think that might be biting off more than I can code. To get me started, have you all implemented blobs in this? if so, how can I redirect the GDScript save, load, and preload to the blob objects?

Thanks for any help.

**Comment by TGRCdev** [comment]
I have added BLOB support, opened a pull request, and released a [nightly build](https://github.com/TGRCdev/gdsqlite-native/releases/tag/nightly-3) containing the new changes. I've tested it and it seems to work fine, but let me know if any errors happen with binding arguments.

As for actually using BLOB data, Godot is very particular about loading and modifying data. For image data, I have found a way to compress, store, retrieve and decompress an image, so long as you know the original width+height, format, compression method, and uncompressed size.

*NOTE: I am not an expert on compression/serialization through GDScript, so a lot of this method may be unnecessary. I highly recommend you study Godot's documentation and come up with a workflow through GDScript that best suits your project.*

Compressing and Storing an Image
---

Say we use the default icon.png. It's a 64x64 image in the RGBA8 format, so each pixel uses 4 bytes of data, or one integer each.
```gdscript
var img_data = preload("res://icon.png")
img_data = img_data.get_data() # Texture -> Image
var width = img_data.get_width()
var height = img_data.get_height()
var format = img_data.get_format()
img_data = img_data.get_data() # Image -> PoolByteArray
var orig_size = img_data.size()
```
(Note: Images should be decompressed before retrieving raw data with `Image.get_data()`. Check `Image.is_compressed()` and use `Image.decompress()`.)

We take the raw image data and compress it using FastLZ
```gdscript
img_data = img_data.compress(File.COMPRESSION_FASTLZ);
```

Now we make a table that can hold this image data. I'll also include the width, height, image format and uncompressed size to keep this demonstration simple.
```gdscript
var db = SQLite.new()
db.open("user://images.db")
db.query("""CREATE TABLE IF NOT EXISTS images (
    id INTEGER PRIMARY KEY, 
    data BLOB, 
    width INTEGER, 
    height INTEGER, 
    format INTEGER,
    full_size INTEGER
    );""")
```

Finally, insert the data and metadata into a row.
```gdscript
db.query_with_args("""INSERT INTO images (
    id, data, width, height, format, full_size
    ) VALUES (?, ?, ?, ?, ?, ?);""", [0, img_data, width, height, format, orig_size])
```

Retrieving and Decompressing Image Data
---
Now, we can retrieve the data by reversing our steps.
Get an image's row by its Primary Key (`id` in this instance)
```gdscript
var results = db.fetch_assoc_with_args("""
    SELECT * FROM images WHERE id=? LIMIT 1""", [0])
results = results[0] # Only one row would be returned
```

Pull out its data and metadata
```gdscript
var data = results["data"]
var width = results["width"]
var height = results["height"]
var format = results["format"]
var max_size = results["full_size"]
````

Decompress the image data
```gdscript
data = data.decompress(max_size, File.COMPRESSION_FASTLZ)
```

Create a new Image object and provide it with your image data
```gdscript
var img = Image.new()
var gen_mipmaps = false;
img.create_from_data(width, height, gen_mipmaps, format, data)
# OPTIONAL: Recompress the image
var lossy_quality = 0.8;
img.compress(
Image.COMPRESS_S3TC, 
Image.COMPRESS_SOURCE_GENERIC, 
lossy_quality
);
```

`img` should now contain an exact copy of your original image data.

*Once again, this was a first attempt at compressing, storing, and loading image data using GDScript. PLEASE experiment with Godot's GDScript API and come up with a workflow that best suits your project.*

**Comment by toboRlivE** [comment]
Wow, you all are knocking it out of the park! That was way more than I was expecting. I'll give you suggestions a try. Thanks again for all your work.
