### ISSUE TITLE
Open connection with flags/arguments

### ISSUE THREAD

**Issue by starwolfy** [khairul169/gdsqlite-native#46]
How does one open up a database connection with arguments? I'd like to have multi-threaded connections with the flag SQLITE_OPEN_NOMUTEX .

**Comment by TGRCdev** [comment]
I added methods for using open flags while opening databases. You can try them out [here](https://github.com/TGRCdev/gdsqlite-native/releases/tag/nightly-7).

**Comment by starwolfy** [comment]
@TGRCdev Stunningly fast work, thanks a lot!
